# Generated by Django 5.1.7 on 2025-03-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0002_ayuntamiento"),
    ]

    operations = [
        migrations.AddField(
            model_name="ayuntamiento",
            name="comunidad",
            field=models.CharField(
                choices=[
                    ("Andalucía", "Andalucía"),
                    ("Aragón", "Aragón"),
                    ("Asturias", "Asturias"),
                    ("Cantabria", "Cantabria"),
                    ("Castilla-La Mancha", "Castilla-La Mancha"),
                    ("Castilla y León", "Castilla y León"),
                    ("Cataluña", "Cataluña"),
                    ("Extremadura", "Extremadura"),
                    ("Galicia", "Galicia"),
                    ("Madrid", "Madrid"),
                    ("Murcia", "Murcia"),
                    ("Navarra", "Navarra"),
                    ("La Rioja", "La Rioja"),
                    ("País Vasco", "País Vasco"),
                    ("Valencia", "Valencia"),
                    ("Ceuta", "Ceuta"),
                    ("Melilla", "Melilla"),
                ],
                default="Valencia",
                max_length=100,
            ),
        ),
    ]
