# Generated by Django 5.1.7 on 2025-03-18 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0004_oposicion_categoria_oposicion_comunidad"),
    ]

    operations = [
        migrations.CreateModel(
            name="OposicionBOE",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("enlace", models.URLField(unique=True)),
                ("fecha_publicacion", models.DateField()),
                ("fuente", models.CharField(default="BOE", max_length=100)),
            ],
        ),
    ]
