# Generated by Django 5.1.7 on 2025-03-19 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0005_oposicionboe"),
    ]

    operations = [
        migrations.AddField(
            model_name="oposicionboe",
            name="descripcion",
            field=models.TextField(default="Sin descripción"),
        ),
        migrations.AddField(
            model_name="oposicionboe",
            name="ministerio",
            field=models.CharField(default="No especificado", max_length=255),
        ),
    ]
